# Generated by Django 4.1.3 on 2022-12-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20210120_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='email',
            name='body',
        ),
        migrations.RemoveField(
            model_name='email',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='email',
            name='read',
        ),
        migrations.RemoveField(
            model_name='email',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='email',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='email',
            name='starred',
        ),
        migrations.RemoveField(
            model_name='email',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='email',
            name='user',
        ),
        migrations.AddField(
            model_name='email',
            name='attach',
            field=models.FileField(blank=True, upload_to='doc'),
        ),
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='email',
            name='message',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='email',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
