# Generated by Django 4.1.3 on 2022-12-08 11:02

from django.db import migrations, models
import mail.models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0006_alter_email_attach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(default=mail.models.recipient, max_length=50),
        ),
    ]
