# Generated by Django 4.1.3 on 2022-12-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0007_alter_email_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='attach',
            field=models.FileField(blank='', default='mail\\CSBS IIIsem.pdf', upload_to='doc'),
        ),
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
