# Generated by Django 4.1.3 on 2022-12-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0009_alter_email_attach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='attach',
        ),
    ]
